config/routes.rb
resources :custom_fields, only: [] do
  resources :values, only: [ :new, :create ], controller: "custom_field/values"
end

app/controllers/custom_field/values_controller.rb
class CustomField::ValuesController < ApplicationController
  unloadable

  helper :custom_fields

  before_filter :find_custom_field, :find_project, :find_customized,
                :find_tracker, :find_custom_value, :authorize_editing

  def new
    respond_to do |format|
      format.js
    end
  end

  def create
    @custom_field.add_possible_values params[:value]
    @custom_field.save
    @custom_value.custom_field = @custom_field
    @with_label = params[:with_label] == '1'
    respond_to do |format|
      format.js
    end
  end

  private

  def find_custom_value
    @custom_value = @customized.custom_field_values.find { |v| v.custom_field_id == @custom_field.id }
  end

  def find_tracker
    if @customized.is_a?(Issue)
      @customized.tracker ||= Tracker.find(params[:tracker_id])
    end
  end

  def find_custom_field
    @custom_field = CustomField.find(params[:custom_field_id])
  end

  def find_customized
    klazz = params[:customized_type].constantize
    @customized = if params[:customized_id].present?
      klazz.find params[:customized_id]
    else
      klazz.new
    end
    if klazz.method_defined?(:project)
      if @customized.project.nil?
        if klazz.method_defined?(:project=)
          @customized.project = @project
        end
      else
        @project = @customized.project
      end
    end
  end

  def find_project
    @project = Project.find(params[:project_id]) if params[:project_id].present?
  end

  def authorize_editing
    if !@custom_value || !User.current.allowed_to_edit?(@customized, @project)
      deny_access
    end
  end
end

app/views/custom_field/values/_new_modal.html.erb
<h3 class="title"><%=l(:custom_field_value_new)%></h3>

<%= form_tag custom_field_values_path(@custom_field, params.slice(:name, :customized_id, :customized_type, :project_id, :tracker_id, :with_label)), remote: true do %>
  <div class="box">
    <p><%= text_area_tag :value, nil, required: true, rows: 10, class: 'wiki-edit' %></p>
  </div>

  <p class="buttons">
    <%= submit_tag l(:button_create) %>
    <%= submit_tag l(:button_cancel), onclick: "hideModal(this)", type: 'button' %>
  </p>
<% end %>

app/views/custom_field/values/create.js.erb
<% tag_id = custom_field_tag_id(params[:name], @custom_field) %>
<% tag_name = custom_field_tag_name(params[:name], @custom_field) %>

var selected;

// save selected values
var $select = $("select[id='<%= tag_id %>']");
if ($select.size()) {
  // custom field is select
  selected = $select.val();
} else {
  // custom field is checkboxes or radiobuttons
  selected = $("[name='<%= tag_name %>']:checked").map(
    function(i, o) { return $(o).val() }).get();
}

// replace with new custom field
var $parent = $("[id='<%= custom_field_add_new_id(params[:name], @custom_field) %>']").parent();
<% if @with_label %>
  $parent.html("<%= escape_javascript(custom_field_tag_with_label params[:name], @custom_value) %>");
<% else %>
  $parent.html("<%= escape_javascript(custom_field_tag params[:name], @custom_value) %>");
<% end %>

// restore selected values
$select = $("select[id='<%= tag_id %>']");
if ($select.size()) {
  // custom field is select
  $select.val(selected);
} else {
  // custom field is checkboxes or radiobuttons
  $("[name='<%= tag_name %>']").each(
    function(i, o) {
      $(o).prop("checked", selected.indexOf($(o).val()) != -1);
    });
}
hideModal();

app/views/custom_field/values/new.js.erb
$('#ajax-modal').html('<%= escape_javascript(render partial: 'custom_field/values/new_modal') %>');
showModal('ajax-modal', '600px');

app/views/list/_dynamic_supported_field.html.erb
<% if custom_field.format.dynamic_supported %>
<p>
  <%= form.check_box :dynamic %>
</p>
<% end %>